### ISSUE TITLE
Hangs on Real Hardware

### ISSUE THREAD

**Issue by OzHawk** [gameblabla/flappybird_vz200#1]
I tried to run your program on a real VZ200 and VZ300 (with and without 16K RAM expansion).  I was able to load the WAV file using an audio player on a PC, and the program loaded (I believe correctly), however it hung when the game started and first tried to update the game screen.
I've seen the video of the game running on an emulator, so I assume this is a difference between real hardware and emulation.

**Comment by gameblabla** [comment]
Ugh, this sucks. I'm always getting surprises such as this one...
I do not own a real VZ200 so that makes testing a little more difficult but it was tested on MAME.
Does it display the titlescreen (the text) properly ?
If so then it's an issue with the clearscreen function that i had modified.
Or maybe it's z88dk not compiling good code :(

I'll send you another build with a different clearscreen function in a few hours.

**Comment by OzHawk** [comment]
Hi,

It displays the title screen (text) correctly and then after one button 
press (not two as you indicated) it starts the game.  It displays the 
whole game screen and then erases most of it but hangs halfway through 
either erasing or redisplaying (not sure which) the flappybird sprite.  
Always seems to hang at the same spot within the sprite.

There's no big rush.  I was happy to get it to load.  It was the first 
time I've tried loading WAV files onto the real hardware. Usually I just 
load people's programs in an emulator but I'm trying to get more use out 
of my real hardware, and have some great software to show off at the 
Retro Computer Club meet. ;^)

Cheers,

Mike

**Comment by gameblabla** [comment]
Okay, so this may be an issue with the assembly routine.
I fixed it (i think), can you give it a try?
https://github.com/gameblabla/flappybird_vz200/raw/master/flappy.wav
https://github.com/gameblabla/flappybird_vz200/raw/master/flappy.vz
https://github.com/gameblabla/flappybird_vz200/raw/master/flappy.cas

If this fix works on real hw, i'll make a new release.
Thanks !

**Comment by OzHawk** [comment]
Unfortunately that fix didn't work.

I've taken a video of the failure and hopefully slo-moed the part where it fails so you can see what updates to the screen it does before it hangs.  The failure was a bit different this time, going past the garbage screen and back to a changed colour flappybird before it hung.

[Flappybird2.wav](https://drive.google.com/open?id=0Byj4lA8_GtwfbGdyZDBKdXRJYzg)

Mike

**Comment by gameblabla** [comment]
Thanks for the video, it seems that the refresh function is still the culprit. :(
The game does not refresh all the time, only each 2 frames. And incidentally, it crashes where it is supposed to refresh.
I need to find another way to clear the whole screen...

**Comment by bushy555** [comment]
...long time between drinks. How are you clearing the screen?   
Are you still using this?
void __FASTCALL__ clearscreen()
{
	#asm
	ld	hl,7000h	; base of graphics area
	ld	(hl),0
	ld	d,h
	ld	e,1			; de	= base_graphics+1
	ld	bc,2730
	ldir				; reset graphics window (2K)
	#endasm
}

There are still a number of bugs within the compilation of Z88 unfortunately that I have found over the years. Works fine within VZEM, but then crashes on real hardware.

In one of my unfinished games from 2002 (which runs on real hardware), I was simply using Z88's vz library of the call routine : 	memset(<dest>,<value>,<count>);
and using :         memcpy(<src>,<dst>,<count>);  to copy to & from the main screen to the screen buffer.

cheers.

**Comment by gameblabla** [comment]
Thanks, using memset(0x7000, 0, 2048); works too. Unfortunately, it seems that pressing keys using the latest z88dk is now unresponsive... Maybe it's on my end though... I should probably not use z88dk's graphical and input routines as they are too generic and suck for games. But probably for a later time.
I've pushed a commit with my changes.

**Comment by gameblabla** [comment]
Feel free to open the issue again if it still doesn't work as i consider it to be fixed.
